remove some mistakes
ok-technopolis-autumn-2019/Bogdan_Maschenko pull request #1
Opened 2019-10-02 21:28 UTC by BogdanMendli

2019-10-06 21:29 UTC, fromanywhere requested changes

2019-10-06 21:29 UTC, fromanywhere commented on index.html
> +                    <div class="main-content_main-section_action-group1">
Нумеровать блоки в классах — не слишком удачная идея для нашего случая. Так иногда действительно делают, когда нужно, например, очень по-разному застилизовать смежные блоки, а осмысленное название придумать тяжело. Но в нашем макете такой проблемы нет, суффикс избыточен.

Я бы подумал над длиной класса. Здесь идея такая — чем длиннее имя класса, тем сложнее его читать и проще запутаться. Код пишут один раз, а читают много раз, поэтому о читаемости важно помнить. С другой стороны, до однобуквенных классов скатываться тоже нехорошо. Впрочем, это не блокер

2019-10-06 21:29 UTC, fromanywhere commented on index.html
> +                        <label class="main-content_main-section_action-group1_label">
Здесь label — совсем не хорошо. Клик будет ставить галку в чекбоксе, а если бы чекбокса не было, то заодно нажималась бы кнопка. С одной стороны, налицо проблема проектирования — как потом добавлять редактирование элемента?, — с другой, проблема неопределенности — что всё-таки должен делать клик?, с третьей — а в чем вообще была идея?

2019-10-06 21:29 UTC, fromanywhere commented on index.html
> +                            <input
В этих input не хватает name с одинаковыми значениями. Браузер не сможет понять, что это единая группа элементов, и я смогу выбрать несколько вариантов одновременно.

В этих input не хватает value. Нам нужно понимать, какой вариант выбран, и брать его из текстового описания в span — совсем нехорошо, там же может быть написано всё, что угодно. Поэтому нужно использовать правильный атрибут для значения

2019-10-06 21:29 UTC, fromanywhere commented on index.html
> +                                    class="main-content_conclusion-bar-group_left-component_items"
Не поднимая дискуссию о читаемости имени класса (длинноват) отмечу, что упоминания позиционирования и стилизации в именовании всегда признак подумать о том, что происходит. Здесь лучше сгруппировать вложенные элементы в три блока — блок под статус, блок под фильтр и блок под кнопку. Тогда у всех трех блоков будут одинаковые имена классов. Думать о том, как они там будут выровнены, нам сейчас не нужно

2019-10-06 21:29 UTC, fromanywhere commented on index.html
> +                                    aria-label="Whats need to be done?"
Здесь лучше не дублировать плейсхолдер, а расширить, рассматривать как пояснение, потому что читалка может просто дважды зачитать один и тот же текст сейчас, а понятнее от этого в два раза не станет

2019-10-06 21:29 UTC, fromanywhere commented on index.html
>  <!DOCTYPE html>
Очень хороший прогресс, но ниже есть несколько критичных замечаний

2019-10-06 21:38 UTC, BogdanMendli commented on index.html
>  <!DOCTYPE html>
Спасибо, исправлю замечания!

2019-10-09 06:47 UTC, fromanywhere commented on index.html
> +                    <div class="main-content_main-section_action-group1">
Здесь всё еще избыточные суффиксы

2019-10-09 07:19 UTC, fromanywhere approved these changes

2019-10-09 07:36 UTC, merged