Task3
ok-technopolis-autumn-2019/Bogdan_Maschenko pull request #2
Opened 2019-10-11 20:12 UTC by BogdanMendli

2019-10-13 17:30 UTC, fromanywhere requested changes

2019-10-13 17:30 UTC, fromanywhere commented on index.css
> +    display: none;
Сразу смотрите, клавиатурная навигация поломалась из-за такого. Первым делом в жизни всегда регресс-тест прогоняют, хоть даже и руками

2019-10-13 17:30 UTC, fromanywhere commented on index.css
> +    word-wrap: break-word;
Хорошая попытка, но нет (но почти) 
![image](https://user-images.githubusercontent.com/1042969/66719380-6d6bd800-edf7-11e9-86f0-d57e9fcf5f4d.png)

2019-10-13 17:30 UTC, fromanywhere commented on index.css
> +    position: absolute;
Крестики там по ховеру появляются в макете

2019-10-13 17:30 UTC, fromanywhere commented on index.css
> +    border: 1px solid #EBDFDF;
Не, ну так неспортивно. Здесь должен быть такой же подход, как у чекбоксов, от состояния радио

2019-10-13 17:30 UTC, fromanywhere commented on index.css
> +    background-image: url(image/close.png);
Из-за того, что у картинки непрозрачный фон, на ховер видны артефакты

2019-10-13 17:30 UTC, fromanywhere commented on index.css
> +    position: absolute;
Здесь площадь клика просится больше 
![image](https://user-images.githubusercontent.com/1042969/66719413-10bced00-edf8-11e9-8f0d-446ff369204d.png)

2019-10-13 17:30 UTC, fromanywhere commented on index.css
> +body {
Это еще не настоящее ревью, это так, чтобы был понятен общий уровень внимания к макету. Но вообще объём проделанной работы я оценил, да

2019-10-13 17:59 UTC, BogdanMendli commented on index.css
> +    background-image: url(image/close.png);
Я вот пробовал уже и сам делать прозрачный фон, хотя в репозитории главном в этой организации он и так вроде прозрачный, но не помогает

2019-10-13 18:09 UTC, fromanywhere commented on index.css
> +    background-image: url(image/close.png);
Хорошо, я был неправ, здесь дело не в картинке. Попробуйте background-color: transparent; вместо #fff

2019-10-13 18:11 UTC, BogdanMendli commented on index.css
> +    background-image: url(image/close.png);
Точно, спасибо)

2019-10-15 09:52 UTC, fromanywhere requested changes

2019-10-15 09:52 UTC, fromanywhere commented on index.css
> +    position: absolute;
Хорошо!

2019-10-15 09:52 UTC, fromanywhere commented on index.css
> +}
не хватает стилей на фокус, с клавиатуры непонятно, где я

2019-10-15 09:52 UTC, fromanywhere commented on index.css
> +    background-repeat: no-repeat;
На фокус тоже бы показывать. А то обводка есть, это хорошо, а иконку не видно

2019-10-15 09:52 UTC, fromanywhere commented on index.css
> +.options-bar__items input {
Селектор по тегу широковат, лучше по классу

2019-10-15 09:52 UTC, fromanywhere commented on index.css
> +    margin-left: 85px;
лучше разрулить такое средствами флексбокса, чем ручными пикселами

2019-10-15 09:52 UTC, fromanywhere commented on index.css
> +    position: absolute;
а зачем здесь абсолют?

2019-10-15 09:52 UTC, fromanywhere commented on index.html
> +                        <label class="input-task" for="HTML-checkbox">
Ну нет, теперь получается, что клик по тексту выбирает чекбокс, так быть не должно в этом месте

2019-10-20 21:57 UTC, fromanywhere requested changes

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    line-height: 21px;
Попробуйте ради смеха забить текст заголовку подлиннее и посмотреть, что будет

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    background-image: url(image/down_pointer.png);
В голове нужно держать графику для дисплеев с повышенной четкостью и подключать её через media queries

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +.main-action {
Выглядит ненужным

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    padding: 5px;
Не нужна здесь явно заданная ширина, оно само растянется. Не нужно делать разделители через тени, используйте бордер. Можно привести разные аргументы, почему так, я тут закладки перебирал, пусть будет эта https://habr.com/ru/company/mailru/blog/236021/

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    width: 100%;
Не нужна здесь ширина с высотой

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    width: auto;
не нужна ширина, да и флекс не используется в полной мере. Ладно бы он там за вертикальное выравнивание отвечал, но вроде бы нет

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    position: absolute;
Вот с таким нужно аккуратнее, текст запросто может заползти под контрол, и крестик на фоне текста просто не заметят. Так тоже делают, да, только тогда нужно более агрессивно делать правое поле у контейнера с текстом, чтобы точно не было такого

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    left: 543px;
по правому краю было бы проще

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    margin: 10px;
margin здесь ничего не даст, оно же вынесено из потока абсолютом. А вот площадь крестика можно было бы и побольше сделать, пальцем будет сложно попасть. Идея такая — площадь интерактивного элемента всегда должна быть больше (по возможности), чем инструмент взаимодействия, иначе будет не видно, во что, собственно, жмем. Так вот за пальцем крестик точно будет не видно

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +    width: 570px;
Явно заданная ширина повсюду меня смущает. Ну не верстаются так приложения в вебе, ширина должна сама резолвиться от размеров контейнера-обертки, мы для этого теги друг в друга вкладываем

2019-10-20 21:57 UTC, fromanywhere commented on index.css
> +}
Хочется примерно всё поближе к макету. Тут же даже не в пикселах дело, простая симметрия и математика 
![image](https://user-images.githubusercontent.com/1042969/67166998-96fba500-f39d-11e9-81d4-53ffabcbd952.png)

2019-10-22 15:46 UTC, fromanywhere approved these changes

2019-10-22 15:46 UTC, fromanywhere commented on index.css
> +    border-top: #E6E6E6 1px inset;
я бы убрал здесь эту границу, явно выбивается 
![image](https://user-images.githubusercontent.com/1042969/67304178-1e5f2a80-f4fc-11e9-85c7-2cad97f90a1d.png)

2019-10-22 15:46 UTC, fromanywhere commented on index.css
> +    line-height: 21px;
если поставить здесь 1.2, как я говорил, а не 21px, как в фигме, то текст не будет слипаться 
![image](https://user-images.githubusercontent.com/1042969/67304286-464e8e00-f4fc-11e9-93f2-dd427e2f6099.png)

2019-10-22 16:20 UTC, merged